public class ListDemo {
    public static void ListMethod(){
Set<String> country = new Set<String>();
        Set<String> country2 = new Set<String>();
        country.add('nepal');
        country.add('india');
        country.add('india');
  
        System.debug(country);
country2.add('russiaa');
        country2.addALL(country);
        System.debug(country2);
        
        
        Map<string,string> hell = new map<string,String>();
        hell.put('fruit','apple');
        system.debug(hell);
    }
}