public class SobjectClass {
    public static void demo(){
Account accobj = new Account();
        Player__c playerobj = new Player__c();
       // accobj.name = 'nirvana';
       // insert accobj;
       /* playerobj.goals__c=10.0;
        playerobj.Name='rooney';
        playerobj.first_name__c='wayne';
            playerobj.last_name__c='rooney';
            playerobj.email__c='rooney@gmail.com';
        insert playerobj;*/
        system.debug(playerobj);
        
          
    }
}